#!/bin/sh

# Thanks Patrick Marques <patrickfmarques@gmail.com> for helping with bash

# Travis runs on a old linux distribution which has an old `wget` and certificates
if [ -z "$TRAVIS" ]; then
    WGET_OPTS="--continue --timestamping --no-verbose --show-progress"
else
    WGET_OPTS="--no-check-certificate --progress=dot:mega"
fi

DIR=test/fixtures/analyze/download/downloaded
mkdir -p ${DIR} && cd ${DIR}
wget ${WGET_OPTS} http://registry.npmjs.org/pickles2-contents-editor/-/pickles2-contents-editor-2.0.0-alpha.1.tgz
wget ${WGET_OPTS} https://registry.npmjs.org/couchdb-iterator/-/couchdb-iterator-2.0.2.tgz
wget ${WGET_OPTS} https://registry.npmjs.org/citong/-/citong-1.3.1.tgz
